### ISSUE TITLE
unable to install byteparsing via pip

### ISSUE THREAD

**Issue by dvberkel** [parallelwindfarms/byteparsing#15]
As a reviewer of [_byteparsing: a functional parser combinator for mixed ASCII/Binary data_ ](https://github.com/openjournals/joss-reviews/issues/5293)
I tried to install `byteparsing` via pip
But was unable to do so

## What I did
I created a virtual environment via `python3 -m venv .env` and activiated it with

```fish
source .env/bin/activate.fish
```

Next a ran

```fish
pip install byteparsing
```

Which produces the following output

```plain
Collecting byteparsing
  Downloading byteparsing-0.1.0.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dvberkel/scratch/foreign/byteparsing/.env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4z81gl1b/byteparsing/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4z81gl1b/byteparsing/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4z81gl1b/byteparsing/pip-egg-info
         cwd: /tmp/pip-install-4z81gl1b/byteparsing/
    Complete output (20 lines):
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    WARNING: The wheel package is not available.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4z81gl1b/byteparsing/setup.py", line 25, in <module>
        setup(
      File "/home/dvberkel/scratch/foreign/byteparsing/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/home/dvberkel/scratch/foreign/byteparsing/.env/lib/python3.8/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/dvberkel/scratch/foreign/byteparsing/.env/lib/python3.8/site-packages/setuptools/dist.py", line 718, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/home/dvberkel/scratch/foreign/byteparsing/.env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.ContextualVersionConflict: (docutils 0.19 (/tmp/pip-install-4z81gl1b/byteparsing/.eggs/docutils-0.19-py3.8.egg), Requirement.parse('docutils<0.19'), {'sphinx-rtd-theme'})
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dvberkel** [comment]
On an unrelated note, the pip command seems to install version `0.1.0` whereas your GitHub package list shows a version `0.1.2` to be available.

**Comment by PabRod** [comment]
Actually, v0.1.2 is [on PyPI](https://pypi.org/project/byteparsing/).

I manage to install it without a problem using conda:

```sh
conda create -n testenv python=3.9
conda activate testenv
pip install byteparsing
```
Returns:
```sh
  Downloading byteparsing-0.1.2-py3-none-any.whl (16 kB)
Collecting numpy<2.0.0,>=1.21.2
  Downloading numpy-1.24.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 11.9 MB/s eta 0:00:00
Installing collected packages: numpy, byteparsing
Successfully installed byteparsing-0.1.2 numpy-1.24.2

```

**Comment by PabRod** [comment]
Any clue about what could be wrong, @jhidding?

**Comment by jhidding** [comment]
Yes, I think I upped the minimum Python version to 3.9 in between releases. So the newest one compatible with 3.8 is byteparsing 1.0. That one had a version conflict with docutils, which shouldn't have been in the dependencies in the first place.
